jobs:
- job: macOS
  pool:
    vmImage: 'macOS 10.13'
  timeoutInMinutes: 150
  steps:
  - script: |
    mvn -v
    mvn clean install
  displayName: 'Build Ballerina'
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  timeoutInMinutes: 150
  steps:
  - script: |
      wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      tar xzf apache-maven-3.5.4-bin.tar.gz
      export PATH=$(pwd)/apache-maven-3.5.4/bin:$PATH
    displayName: 'Setting up Maven'
  - script: |
      mvn -v
      mvn clean install
    displayName: 'Build Ballerina'
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  timeoutInMinutes: 150
  steps:
  - script: |
      mvn -v
      mvn clean install
    displayName: 'Build Ballerina'
